config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tutionships
  root 'welcome#index'
  draw :admin # admin routes 'config/routes/admin.rb'
  draw :api_v1 # api v1 routes 'config/routes/api_v1.rb'
  draw :web # api v1 routes 'config/routes/web.rb'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :users
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :tution_class
  has_many :tutionships
  has_many :users, through: :tutionships

  def subject_display
    "#{self.name} - #{self.tution_class.name}"
  end
end

app/models/system_preference.rb
class SystemPreference < ApplicationRecord
  after_commit :remove_cache

  def self.[](key)
    return nil if key.nil?

    preference = Rails.cache.fetch("preference_key_#{key.to_s.downcase.parameterize(separator: '_')}", expires_in: 30.days) do
      find_by(key: key)&.value
    end

    return preference if preference.present?

    preference = create(key: key, value: ENV[key.to_s].presence) if ENV[key.to_s].present?

    return preference&.value
  end

  def self.[]=(key, value)
    pref = find_or_initialize_by(key: key)
    pref.value = value
    pref.save

    self[key]
  end

  def self.clear!
    delete_all
  end

  def self.fetch(key, fallback = nil, force_assign = true)
    return (self[key] ||= fallback.respond_to?(:call) ? fallback.call : fallback) if fallback && force_assign

    self[key] || fallback
  end

  def remove_cache
    Rails.cache.delete("preference_key_#{self.key.downcase.parameterize(separator: '_')}") if self.key.present?
  end
end

app/models/tution_class.rb
class TutionClass < ApplicationRecord
  has_many :subjects

  enum level: %i[school college university]
end

app/models/tutionship.rb
class Tutionship < ApplicationRecord
  belongs_to :user
  belongs_to :subject
end

app/models/university.rb
class University < ApplicationRecord
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  include DeviseTokenAuth::Concerns::User

  belongs_to :school, optional: true
  belongs_to :college, optional: true
  belongs_to :university, optional: true
  has_many :tutionships
  has_many :subjects, through: :tutionships
  accepts_nested_attributes_for :tutionships, allow_destroy: true

  validates_presence_of :full_name

  mount_uploader :image, AvatarUploader

  enum sex: %i[male female other]
  enum role: %i[teacher student guardian]

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

  private

    def college_params
      params.require(:college).permit(:name, :address)
    end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  private

    def school_params
      params.require(:school).permit(:name, :address)
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  private

    def subject_params
      params.require(:subject).permit(:name, :tution_class_id)
    end

end

app/controllers/tutionships_controller.rb
class TutionshipsController < InheritedResources::Base

  private

    def tutionship_params
      params.require(:tutionship).permit(:user_id, :tution_class_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tution_classes_helper.rb
module TutionClassesHelper
end

app/helpers/tutionships_helper.rb
module TutionshipsHelper
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tutionships/_form.html.erb
<%= form_with(model: tutionship, local: true) do |form| %>
  <% if tutionship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutionship.errors.count, "error") %> prohibited this tutionship from being saved:</h2>

      <ul>
        <% tutionship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :tution_class_id %>
    <%= form.number_field :tution_class_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutionships/edit.html.erb
<h1>Editing Tutionship</h1>

<%= render 'form', tutionship: @tutionship %>

<%= link_to 'Show', @tutionship %> |
<%= link_to 'Back', tutionships_path %>

app/views/tutionships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutionships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tution class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutionships.each do |tutionship| %>
      <tr>
        <td><%= tutionship.user_id %></td>
        <td><%= tutionship.tution_class_id %></td>
        <td><%= link_to 'Show', tutionship %></td>
        <td><%= link_to 'Edit', edit_tutionship_path(tutionship) %></td>
        <td><%= link_to 'Destroy', tutionship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutionship', new_tutionship_path %>

app/views/tutionships/new.html.erb
<h1>New Tutionship</h1>

<%= render 'form', tutionship: @tutionship %>

<%= link_to 'Back', tutionships_path %>

app/views/tutionships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @tutionship.user_id %>
</p>

<p>
  <strong>Tution class:</strong>
  <%= @tutionship.tution_class_id %>
</p>

<%= link_to 'Edit', edit_tutionship_path(@tutionship) %> |
<%= link_to 'Back', tutionships_path %>